apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment 
  namespace: roboshop
  labels: # these belong to deployment labels
    app: payment
    tier: app 
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labes should match with pod
      app: payment
      tier: app 
      project: roboshop
  template: # this is the pod defination 
    metadata:
      labels:
        app: payment
        tier: app 
        project: roboshop
    spec:
      containers:
      - name: payment
        image: praveenkothapally/payment:1.0.0
        envFrom:
        - configMapRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: roboshop
spec:
  selector: #below are lables from above pod 
    app: payment
    tier: app 
    project: roboshop
  ports:
  - name: payment-port 
    protocol: TCP
    port: 8080 # this port belogs to service
    targetPort: 8080 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
  namespace: roboshop
data: 
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user"
  USER_PORT: "8080"
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"