apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping 
  namespace: roboshop
  labels: # these belong to deployment labels
    app: shipping
    tier: app 
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labes should match with pod
      app: shipping
      tier: app 
      project: roboshop
  template: # this is the pod defination 
    metadata:
      labels:
        app: shipping
        tier: app 
        project: roboshop
    spec:
      containers:
      - name: shipping
        image: praveenkothapally/shipping:1.0.0
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector: #below are lables from above pod 
    app: shipping
    tier: app 
    project: roboshop
  ports:
  - name: shipping-port 
    protocol: TCP
    port: 8080 # this port belogs to service
    targetPort: 8080 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data: 
  CART_ENDPOINT: "cart:8080"
  DB_HOST: mysql
