apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # these belong to deployment labels
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels: # these labes should match with pod
      app: nginx
      project: roboshop
      component: frontend
  template: # this is the pod defination 
    metadata:
      labels:
        app: nginx
        project: roboshop
        component: frontend 
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
