apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels: # these belong to deployment labels
    app: mysql
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labes should match with pod
      app: mysql
      tier: db
      project: roboshop
  template: # this is the pod defination 
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: praveenkothapally/mysql:1.0.0
        envFrom:
        - configMapRef:
            name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector: #below are lables from above pod 
    app: mysql
    tier: db
    project: roboshop
  ports:
  - name: mysql-port 
    protocol: TCP
    port: 3306 # this port belogs to service
    targetPort: 3306 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data: 
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "Roboshop@1"

